# Generated by Django 4.1.2 on 2022-10-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='customer',
        ),
    ]
