# Generated by Django 4.1.2 on 2022-10-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='paid',
        ),
    ]
